#
# This file is part of Brazil Data Cube Collection Builder.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

version: '3.1'

networks:
  bdc_net:

services:
  redis:
    image: redis
    container_name: bdc-collection-builder-redis
    restart: "always"
    ports:
      - "6379:6379"
    networks:
      - bdc_net

  mq:
    image: rabbitmq:3-management
    container_name: bdc-collection-builder-rabbitmq
    hostname: bdc-collection-builder-rabbitmq
    restart: "always"
    volumes:
      - "./volumes/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bdc_net

  postgres:
    image: mdillon/postgis
    container_name: bdc-collection-builder-pg
    restart: "always"
    shm_size: 1gb
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=postgres"
    networks:
      - bdc_net
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: bdc-collection-builder-api
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@bdc-collection-builder-pg:5432/bdc"
      - "DATA_DIR=/data"
    networks:
      - bdc_net
    ports:
      - "5000:5000"
    volumes:
      - /data:/data
    command: >
      bash -c "bdc-collection-builder run --host 0.0.0.0"
    depends_on:
      - mq
      - redis
      - postgres

#  Celery
  worker-download:
    container_name: bdc-collection-builder-worker-download
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - api
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@bdc-collection-builder-pg:5432/bdc"
      - "DATA_DIR=/data"
    volumes:
      - /data:/data
    command: >
      celery -A bdc_collection_builder.celery.worker:celery worker -l INFO --concurrency 2 -Q download
    networks:
      - bdc_net

  worker-atm-correction:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.atm
    container_name: bdc-collection-builder-worker-atm-correction
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder-atm:latest
    restart: "always"
    depends_on:
      - mq
      - api
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@bdc-collection-builder-pg:5432/bdc"
      - "DATA_DIR=/data"
      # The following variables are related to laSRC and ledaps execution.
      - "L8_AUX_DIR=/mnt/auxiliaries/L8"
      - "LEDAPS_AUX_DIR=/mnt/auxiliaries/ledaps"
      # Sen2cor
      - "SEN2COR_DOCKER_IMAGE=registry.dpi.inpe.br/brazildatacube/sen2cor:2.8.0"
      - "SEN2COR_AUX_DIR=/mnt/auxiliaries/sen2cor/CCI4SEN2COR"
      - "SEN2COR_CONFIG_DIR=/mnt/auxiliaries/sen2cor/config/2.8"
      # LaSRC
      - "LASRC_DOCKER_IMAGE=registry.dpi.inpe.br/brazildatacube/lasrc-ledaps-fmask:1.0.4"
      - "LASRC_AUX_DIR=/mnt/auxiliaries/L8"
      - "LEDAPS_AUX_DIR=/mnt/auxiliaries/ledaps_auxiliaries"
    volumes:
      - /data:/data
      - /mnt/auxiliaries:/mnt/auxiliaries
    entrypoint: ["celery", "worker", "-A", "bdc_collection_builder.celery.worker:celery", "-l", "INFO", "--concurrency", "2", "-Q", "atm-correction"]
    networks:
      - bdc_net

  worker-publish:
    container_name: bdc-collection-builder-worker-publish
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - api
    volumes:
      - /data:/data
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "DATA_DIR=/data"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@bdc-collection-builder-pg:5432/bdc"
    command: >
        celery worker -A bdc_collection_builder.celery.worker:celery -l INFO --concurrency 2 -Q publish
    networks:
      - bdc_net
