"""empty message

Revision ID: 27e54f487f16
Revises: 7ae47c138adf
Create Date: 2019-11-12 10:27:26.278640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e54f487f16'
down_revision = '7ae47c138adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('task_id', sa.Integer(), nullable=False), schema='radcor')
    op.create_unique_constraint(None, 'activities', ['id'], schema='radcor')
    op.create_foreign_key(None, 'activities', 'celery_taskmeta', ['task_id'], ['id'], source_schema='radcor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', schema='radcor', type_='foreignkey')
    op.drop_constraint(None, 'activities', schema='radcor', type_='unique')
    op.drop_column('activities', 'task_id', schema='radcor')
    # ### end Alembic commands ###
