"""Add catalog models

Revision ID: 62cf6dc5d2a4
Revises: 81bdb7b04a9a
Create Date: 2019-11-14 09:56:31.764177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cf6dc5d2a4'
down_revision = '81bdb7b04a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Dataset', sa.String(length=50), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.Column('ProcessingDate', sa.DateTime(), nullable=True),
    sa.Column('GeometricProcessing', sa.String(length=20), nullable=False),
    sa.Column('RadiometricProcessing', sa.String(length=20), nullable=False),
    sa.Column('SceneId', sa.String(length=64), nullable=False),
    sa.Column('Band', sa.String(length=20), nullable=False),
    sa.Column('Resolution', sa.Float(), nullable=True),
    sa.Column('Filename', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    schema='catalogo'
    )
    op.create_table('Dataset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    schema='catalogo'
    )
    op.create_table('Qlook',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('SceneId', sa.String(length=64), nullable=False),
    sa.Column('QLfilename', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('SceneId'),
    sa.UniqueConstraint('QLfilename'),
    schema='catalogo'
    )
    op.create_index(op.f('ix_catalogo_Qlook_SceneId'), 'Qlook', ['SceneId'], unique=False, schema='catalogo')
    op.create_table('Request',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ReqId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.String(length=254), nullable=False),
    sa.Column('ReqDate', sa.DateTime(), nullable=False),
    sa.Column('StatusDate', sa.DateTime(), nullable=False),
    sa.Column('PayDate', sa.DateTime(), nullable=True),
    sa.Column('DelDate', sa.DateTime(), nullable=True),
    sa.Column('Priority', sa.Integer(), nullable=False),
    sa.Column('Operator', sa.String(length=20), nullable=False),
    sa.Column('addressId', sa.Integer(), nullable=False),
    sa.Column('Ip', sa.String(length=20), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('Language', sa.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('ReqId'),
    schema='catalogo'
    )
    op.create_table('Scene',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('SceneId', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('IdRunMode', sa.Integer(), nullable=True),
    sa.Column('Satellite', sa.String(length=50), nullable=True),
    sa.Column('Sensor', sa.String(length=6), nullable=False),
    sa.Column('Path', sa.String(length=11), nullable=True),
    sa.Column('Row', sa.String(length=11), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Orbit', sa.Integer(), nullable=True),
    sa.Column('CenterLatitude', sa.Float(), nullable=True),
    sa.Column('CenterLongitude', sa.Float(), nullable=True),
    sa.Column('TL_Latitude', sa.Float(), nullable=True),
    sa.Column('TL_Longitude', sa.Float(), nullable=True),
    sa.Column('BR_Latitude', sa.Float(), nullable=True),
    sa.Column('BR_Longitude', sa.Float(), nullable=True),
    sa.Column('TR_Latitude', sa.Float(), nullable=True),
    sa.Column('TR_Longitude', sa.Float(), nullable=True),
    sa.Column('BL_Latitude', sa.Float(), nullable=True),
    sa.Column('BL_Longitude', sa.Float(), nullable=True),
    sa.Column('CenterTime', sa.Float(asdecimal=True), nullable=True),
    sa.Column('StartTime', sa.Float(asdecimal=True), nullable=True),
    sa.Column('StopTime', sa.Float(asdecimal=True), nullable=True),
    sa.Column('ImageOrientation', sa.Float(), nullable=True),
    sa.Column('SyncLosses', sa.Integer(), nullable=True),
    sa.Column('NumMissSwath', sa.Integer(), nullable=True),
    sa.Column('PerMissSwath', sa.Float(), nullable=True),
    sa.Column('BitSlips', sa.Integer(), nullable=True),
    sa.Column('CloudCoverQ1', sa.Integer(), nullable=True),
    sa.Column('CloudCoverQ2', sa.Integer(), nullable=True),
    sa.Column('CloudCoverQ3', sa.Integer(), nullable=True),
    sa.Column('CloudCoverQ4', sa.Integer(), nullable=True),
    sa.Column('CloudCoverMethod', sa.CHAR(length=1), nullable=True),
    sa.Column('Grade', sa.Float(), nullable=True),
    sa.Column('IngestDate', sa.DateTime(), nullable=True),
    sa.Column('Deleted', sa.SmallInteger(), nullable=False),
    sa.Column('Dataset', sa.String(length=50), nullable=True),
    sa.Column('ExportDate', sa.DateTime(), nullable=True),
    sa.Column('AuxPath', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('SceneId'),
    schema='catalogo'
    )
    op.create_index('Scene_idx1', 'Scene', ['Satellite', 'Sensor'], unique=False, schema='catalogo')
    op.create_index('Scene_idx6', 'Scene', ['CloudCoverQ1', 'CloudCoverQ2', 'CloudCoverQ3', 'CloudCoverQ4'], unique=False, schema='catalogo')
    op.create_index(op.f('ix_catalogo_Scene_Date'), 'Scene', ['Date'], unique=False, schema='catalogo')
    op.create_index(op.f('ix_catalogo_Scene_Path'), 'Scene', ['Path'], unique=False, schema='catalogo')
    op.create_index(op.f('ix_catalogo_Scene_Row'), 'Scene', ['Row'], unique=False, schema='catalogo')
    op.create_index(op.f('ix_catalogo_Scene_Sensor'), 'Scene', ['Sensor'], unique=False, schema='catalogo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogo_Scene_Sensor'), table_name='Scene', schema='catalogo')
    op.drop_index(op.f('ix_catalogo_Scene_Row'), table_name='Scene', schema='catalogo')
    op.drop_index(op.f('ix_catalogo_Scene_Path'), table_name='Scene', schema='catalogo')
    op.drop_index(op.f('ix_catalogo_Scene_Date'), table_name='Scene', schema='catalogo')
    op.drop_index('Scene_idx6', table_name='Scene', schema='catalogo')
    op.drop_index('Scene_idx1', table_name='Scene', schema='catalogo')
    op.drop_table('Scene', schema='catalogo')
    op.drop_table('Request', schema='catalogo')
    op.drop_index(op.f('ix_catalogo_Qlook_SceneId'), table_name='Qlook', schema='catalogo')
    op.drop_table('Qlook', schema='catalogo')
    op.drop_table('Dataset', schema='catalogo')
    op.drop_table('Products', schema='catalog')
    # ### end Alembic commands ###
