"""add datastorm activities

Revision ID: 7ae7f1df8bd6
Revises: 962a0f21f6e8
Create Date: 2019-12-27 10:29:30.089402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae7f1df8bd6'
down_revision = '962a0f21f6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datastorm_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scene_type', sa.String(), nullable=True),
    sa.Column('sceneid', sa.String(length=64), nullable=False),
    sa.Column('band', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datastorm_activity_history',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('env', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['datastorm_activities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['celery_taskmeta.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datastorm_activity_history')
    op.drop_table('datastorm_activities')
    # ### end Alembic commands ###
