"""empty message

Revision ID: 88f1744b1d76
Revises: 0c7320fe1ff6
Create Date: 2019-11-22 16:16:06.984514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f1744b1d76'
down_revision = '0c7320fe1ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_history',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sceneid', sa.String(length=64), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('elapsed', sa.Time(), nullable=True),
    sa.Column('retcode', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['radcor.activities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['celery_taskmeta.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'task_id'),
    schema='radcor'
    )
    op.drop_constraint('activities_task_id_fkey', 'activities', schema='radcor', type_='foreignkey')
    op.drop_column('activities', 'task_id', schema='radcor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='radcor')
    op.create_foreign_key('activities_task_id_fkey', 'activities', 'celery_taskmeta', ['task_id'], ['id'], source_schema='radcor')
    op.drop_table('activity_history', schema='radcor')
    # ### end Alembic commands ###
